version: "3.9"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    volumes:
      - "go-cache:/root/.cache/go-build"
      - "go-mod-cache:/root/.config/go/env"
      - "./:/src"
      - "$HOME/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json"

volumes:
  go-cache:
  go-mod-cache:
